export const Payload = {
  Event: {
    Id: 1,
    CoverImage: "https://fullscale.io/wp-content/uploads/2022/04/fs-logo.png",
    Name: "Year End Party 2023",
    Description: "YEP 2023! Let's goo booooom!",
  },
  EventLogs: [
    {
      Id: 1,
      EventId: 1,
      AttendeeId: 1,
    },
    {
      Id: 2,
      EventId: 1,
      AttendeeId: 2,
    },
    {
      Id: 3,
      EventId: 1,
      AttendeeId: 3,
    },
    {
      Id: 4,
      EventId: 1,
      AttendeeId: 4,
    },
    {
      Id: 5,
      EventId: 1,
      AttendeeId: 5,
    },
    {
      Id: 6,
      EventId: 1,
      AttendeeId: 6,
    },
    {
      Id: 7,
      EventId: 1,
      AttendeeId: 7,
    },
    {
      Id: 8,
      EventId: 1,
      AttendeeId: 8,
    },
    {
      Id: 9,
      EventId: 1,
      AttendeeId: 9,
    },
    {
      Id: 10,
      EventId: 1,
      AttendeeId: 10,
    },
    {
      Id: 11,
      EventId: 1,
      AttendeeId: 11,
    },
    {
      Id: 12,
      EventId: 1,
      AttendeeId: 12,
    },
    {
      Id: 13,
      EventId: 1,
      AttendeeId: 13,
    },
  ],
  Attendees: [
    {
      Id: 1,
      LastName: "Abejar",
      FirstName: "Jayharron Mar",
      MiddleInitial: "C",
      Email: "jabejar@fullscale.io",
    },
    {
      Id: 2,
      LastName: "Cuico",
      FirstName: "Harold",
      MiddleInitial: "T",
      Email: "hcuico@fullscale.io",
    },
    {
      Id: 3,
      LastName: "Acopiado",
      FirstName: "Jhon Mark",
      MiddleInitial: "",
      Email: "jacopiado@fullscale.io",
    },
    {
      Id: 4,
      LastName: "Jumapao",
      FirstName: "Alyssa",
      MiddleInitial: "",
      Email: "ajumapao@fullscale.io",
    },
    {
      Id: 5,
      FirstName: "Wayne Matthew",
      LastName: "Dayata",
      MiddleInitial: "",
      Email: "wdayata@fullscale.io",
    },
    {
      Id: 6,
      FirstName: "Raphael Jess",
      LastName: "Bacordio",
      MiddleInitial: "",
      Email: "rbacordio@fullscale.io",
    },
    {
      Id: 7,
      FirstName: "Rodney",
      LastName: "Fernandez",
      MiddleInitial: "",
      Email: "rofernandez@fullscale.io",
    },
    {
      Id: 8,
      FirstName: "Kenneth",
      LastName: "Dela Cruz",
      MiddleInitial: "",
      Email: "kdelacruz@fullscale.io",
    },
    {
      Id: 9,
      FirstName: "Nealford",
      LastName: "Sotes",
      MiddleInitial: "",
      Email: "nsotes@fullscale.io",
    },
    {
      Id: 10,
      FirstName: "James Dylan",
      LastName: "Caramonte",
      MiddleInitial: "",
      Email: "jcaramonte@fullscale.io",
    },
    {
      Id: 11,
      FirstName: "Xerxes",
      LastName: "Ondong, III",
      MiddleInitial: "",
      Email: "xondongiii@fullscale.io",
    },
    {
      Id: 12,
      FirstName: "Reynald",
      LastName: "Sampelo",
      MiddleInitial: "",
      Email: "rsampello@fullscale.io",
    },
    {
      Id: 13,
      FirstName: "Ada Pauline",
      LastName: "Villacarlos",
      MiddleInitial: "",
      Email: "avillacarlos@fullscale.io",
    },
  ],
};
